---

- name: Install git
  become: true
  become_user: root
  yum:
    name: git
    state: present

- name: Template endpoints json
  template:
    src: glusterfs-endpoints.json.j2
    dest: /home/centos/glusterfs-endpoints.json

- name: Template service json
  template:
    src: glusterfs-service.json.j2
    dest: /home/centos/glusterfs-service.json

- name: Template volume yaml (IT'S STATIC RIGHT NOW, FIX THAT.)
  template:
    src: glusterfs-volumes.yaml.j2
    dest: /home/centos/glusterfs-volumes.yaml

- name: Template namespace yaml
  template:
    src: glusterfs-namespace.yaml.j2
    dest: /home/centos/glusterfs-namespace.yaml

- name: Get list of namespaces
  shell: >
    kubectl get namespaces
  register: namespaces_list

- name: Create gluster namespace if necessary
  shell: >
    kubectl create -f /home/centos/glusterfs-namespace.yaml
  when: "'gluster' not in namespaces_list.stdout"

- name: Clone gluster-kubernetes
  git:
    repo: https://github.com/gluster/gluster-kubernetes.git
    dest: /home/centos/gluster-kubernetes
    version: "{{ gluster_kubernetes_version }}"

- name: Template GlusterFS gk-deploy topology json
  template:
    src: glusterfs-topology.json.j2
    dest: /home/centos/gluster-kubernetes/deploy/topology.json

- name: Download heketi cli tarball
  get_url:
    url: https://github.com/heketi/heketi/releases/download/v4.0.0/heketi-v4.0.0.linux.amd64.tar.gz
    dest: /home/centos/heketi.tar.gz

- name: Create directory for extraction of tarball
  file:
    path: /home/centos/heketi
    state: directory

- name: Extract heketi cli tarball
  unarchive:
    src: /home/centos/heketi.tar.gz
    dest: /home/centos/heketi
    remote_src: yes

- name: Copy heketi-cli bin into place
  become: true
  become_user: root
  shell: >
    cp /home/centos/heketi/heketi/heketi-cli /usr/local/bin/heketi-cli
  args:
    creates: /usr/local/bin/heketi-cli

- name: Deploy GlusterFS on Kubernetes with gk-deploy (note -- this is coffee break worthy, it takes a while)
  shell: >
    ./gk-deploy -n gluster -g -y
  args:
    chdir: /home/centos/gluster-kubernetes/deploy
    creates: /home/centos/.gk-deployed

- name: Mark that gk-deploy is complete
  file:
    path: /home/centos/.gk-deployed
    state: directory

- name: Get the heketi IP address
  shell: >
    kubectl get svc --namespace=gluster | grep 8080 | awk '{print $2}'
  register: heketi_ipaddress_raw

- name: Set the heketi IP
  set_fact:
    heketi_ip: "{{ heketi_ipaddress_raw.stdout }}"

- name: Template the storage class yaml
  template:
    src: glusterfs-storageclass.yaml.j2
    dest: /home/centos/glusterfs-storageclass.yaml

- name: List the storage classes
  shell: >
    kubectl get storageclass
  register: storageclass_list

- name: Create the storage class
  shell: >
    kubectl create -f /home/centos/glusterfs-storageclass.yaml
  when: "'gluster' not in storageclass_list.stdout"

# Get heketi URL.
# [centos@kube-master ~]$ kubectl get svc --namespace=gluster | grep 8080 | awk '{print $2}'
# 10.105.179.111
